### ISSUE TITLE
Support for jqwik

### ISSUE THREAD

**Issue by ragunathjawahar** [approvals/ApprovalTests.Java#134]
I am trying to use ApprovalTests with [jqwik](https://jqwik.net) property based testing library. However, I run into this exception.

```
Could not find Junit/TestNg TestCase you are running, supported frameworks: Junit3, Junit4, Junit5, TestNg
java.lang.RuntimeException: Could not find Junit/TestNg TestCase you are running, supported frameworks: Junit3, Junit4, Junit5, TestNg
	at org.approvaltests.namer.AttributeStackSelector.selectElement(AttributeStackSelector.java:62)
	at com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:175)
	at com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:168)
	at org.approvaltests.namer.StackTraceNamer.<init>(StackTraceNamer.java:15)
	at org.approvaltests.Approvals$1.load(Approvals.java:45)
	at org.approvaltests.Approvals$1.load(Approvals.java:42)
	at org.approvaltests.Approvals.createApprovalNamer(Approvals.java:247)
	at org.approvaltests.core.Options$FileOptions.getNamer(Options.java:90)
	at org.approvaltests.Approvals.verify(Approvals.java:178)
	at org.approvaltests.Approvals.verify(Approvals.java:54)
	at org.approvaltests.Approvals.verify(Approvals.java:50)
	at com.gildedrose.GildedRoseJqwikApprovalTest.goldenMaster(GildedRoseJqwikApprovalTest.kt:35)
```

I find property tests to be quite valuable while attempting to bring legacy code bases under tests. Would like to hear your thoughts on this.

If we come to an agreement, I can raise a PR for this feature request. LMK. Many thanks in advance.

**Comment by ragunathjawahar** [comment]
Duplicate of #133
