### ISSUE TITLE
Flaky approval test

### ISSUE THREAD

**Issue by michelgrootjans-persgroep** [approvals/ApprovalTests.Java#151]
When we run this unit test, we get flaky results.

``` java

import org.approvaltests.reporters.UseReporter;
import org.junit.Test;  // junit 4 !

@UseReporter(JunitReporter.class)
public class FilterCreateVOHelperTest {
    // ...

    @Test
    public void getFilterVOS() {
        verifyAllCombinations(
                this::getFilterVOS,
            //...
        )
    }

    private List<FilterVO> getFilterVOS(...) {
        // ....
    }

    // ....
}
```

 Sometimes the test is green, sometimes it fails with this exception:
```
Could not find Junit/TestNg TestCase you are running, supported frameworks: Junit3, Junit4, Junit5, TestNg
java.lang.RuntimeException: Could not find Junit/TestNg TestCase you are running, supported frameworks: Junit3, Junit4, Junit5, TestNg
	at org.approvaltests.namer.AttributeStackSelector.selectElement(AttributeStackSelector.java:63)
	at com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:199)
	at com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:192)
	at org.approvaltests.namer.StackTraceNamer.<init>(StackTraceNamer.java:18)
	at org.approvaltests.Approvals$1.load(Approvals.java:46)
	at org.approvaltests.Approvals$1.load(Approvals.java:43)
	at org.approvaltests.Approvals.createApprovalNamer(Approvals.java:252)
	at org.approvaltests.core.Options$FileOptions.getNamer(Options.java:90)
	at org.approvaltests.Approvals.verify(Approvals.java:179)
	at org.approvaltests.Approvals.verify(Approvals.java:55)
	at org.approvaltests.Approvals.verify(Approvals.java:64)
	at org.approvaltests.combinations.CombinationsHelper.verifyAllCombinations(CombinationsHelper.java:62)
	at org.approvaltests.combinations.CombinationApprovals.verifyAllCombinations(CombinationApprovals.java:205)
	at org.approvaltests.combinations.CombinationApprovals.verifyAllCombinations(CombinationApprovals.java:194)
	at org.approvaltests.combinations.CombinationApprovals.verifyAllCombinations(CombinationApprovals.java:50)
```

We have a suspicion that this is caused by the overloaded `getFilterVOS` method. We tracked the stacktrace to `org.approvaltests.namer.AttributeStackSelector:84` in the method `isTestAttribute`:
``` java
  private boolean isTestAttribute(Class<?> clazz, String methodName)
      throws ClassNotFoundException, SecurityException
  {
    Method method = getMethodByName(clazz, methodName);
    if (method == null)
    { return false; }
    for (Class<? extends Annotation> attribute : attributes)
    {
      if (method.isAnnotationPresent(attribute))
      { return true; }
    }
    return false;
  }
```

`Method method = getMethodByName(clazz, methodName);` picks one of the overloaded `getFilterVOS` from our test. Sometimes it's the actual test, sometimes it's the one passed to `verifyAllCombinations(...)`. The quickfix for us is obvously: rename one of the methods.

Maybe this could be fixed in a future release of approvaltests.

**Comment by LarsEckart** [comment]
I can confirm that your suspicion is correct. It's not the first time this comes up, I remember one more occurrence but back then we didn't fix it and rather proposed to rename the method.

We'll meet tonight, I'll raise awareness for this issue.

**Comment by LarsEckart** [comment]
part of release 10.4.1 which is building right now
