### ISSUE TITLE
Approval seems to fail under linux

### ISSUE THREAD

**Issue by mike03081972** [approvals/ApprovalTests.Java#33]
Hi,

I'm developing under intellij on windows 10. On this system, the approval process is working fine.
But we are using build  machines using teamcity on a linux machine.
The approval process is failing on linux with such message

junit.framework.ComparisonFailure: expected:<[]> but was:<[{
  "id" : "00000000-0000-0000-0000-000000000001"}]>

The *approved.txt is containing the write json string.

Any idea ?

**Comment by isidore** [comment]
Probably the issue is with the namer. 
you can check this by forcing the quiet reporter.

My guess is that Team City is not copying the .java files and that is making approval testing unable to find the approved file. Although maybe there are other issues, including if Team City is pushing to multiple computers to run the test.

You can force The Quiet Reporter with 
     @UserReporter(QuietReporter.class)

**Comment by mike03081972** [comment]
_This is what I receive_ :

java.lang.Error: Failed Approval
  Approved:/opt/jetbrains/teamcity/buildAgent/work/c1bbf18794ed62ea/./src/itest/java/tests/TestApprovals.testApproval.approved.txt
  Received:/opt/jetbrains/teamcity/buildAgent/work/c1bbf18794ed62ea/./src/itest/java/tests/TestApprovals.testApproval.received.txt
    at org.approvaltests.approvers.FileApprover.fail(FileApprover.java:45)
    at org.approvaltests.Approvals.verify(Approvals.java:140)
    at org.approvaltests.Approvals.verify(Approvals.java:123)
    at org.approvaltests.Approvals.verify(Approvals.java:127)
    at org.approvaltests.Approvals.verify(Approvals.java:58)
    at tests.TestApprovals.testApproval(TestApprovals.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
    at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

------- Stdout: -------
Use nginx : true
nginx : true
hostname : http://10.129.60.251
11:45:27.191 [Test worker] DEBUG org.springframework.web.client.RestTemplate - Created POST request for "http://10.129.60.251/api/timeline/v0/timeline/20a6e606-2857-449b-879d-1a28ce06e69e/00000000-0000-0000-0000-000000000001/open/"
11:45:27.198 [Test worker] DEBUG org.springframework.web.client.RestTemplate - Setting request Accept header to [text/plain, application/json, application/*+json, */*]
11:45:27.199 [Test worker] DEBUG org.springframework.web.client.RestTemplate - Writing [{}] as "application/json" using [org.springframework.http.converter.StringHttpMessageConverter@1a37d1eb]
11:45:27.738 [Test worker] DEBUG org.springframework.web.client.RestTemplate - POST request for "http://10.129.60.251/api/timeline/v0/timeline/20a6e606-2857-449b-879d-1a28ce06e69e/00000000-0000-0000-0000-000000000001/open/" resulted in 201 (null)
11:45:27.742 [Test worker] DEBUG org.springframework.web.client.RestTemplate - Reading [java.lang.String] as "application/json;charset=UTF-8" using [org.springframework.http.converter.StringHttpMessageConverter@1a37d1eb]
[{"connectedUserId":"20a6e606-2857-449b-879d-1a28ce06e69e"}]
11:45:27.754 [Test worker] DEBUG org.springframework.web.client.RestTemplate - Created GET request for "http://10.129.60.251/api/timeline/v0/timeline/20a6e606-2857-449b-879d-1a28ce06e69e/00000000-0000-0000-0000-000000000001/thumbnailview/get/"
11:45:27.803 [Test worker] DEBUG org.springframework.web.client.RestTemplate - Setting request Accept header to [application/json, application/*+json]
11:45:27.916 [Test worker] DEBUG org.springframework.web.client.RestTemplate - GET request for "http://10.129.60.251/api/timeline/v0/timeline/20a6e606-2857-449b-879d-1a28ce06e69e/00000000-0000-0000-0000-000000000001/thumbnailview/get/" resulted in 200 (null)
11:45:27.918 [Test worker] DEBUG org.springframework.web.client.RestTemplate - Reading [interface java.util.Map] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@181dab68]
{
  "id" : "00000000-0000-0000-0000-000000000001"
}
mv /opt/jetbrains/teamcity/buildAgent/work/c1bbf18794ed62ea/./src/itest/java/tests/TestApprovals.testApproval.received.txt /opt/jetbrains/teamcity/buildAgent/work/c1bbf18794ed62ea/./src/itest/java/tests/TestApprovals.testApproval.approved.txt

**Comment by isidore** [comment]
are you checking in your approved files?

**Comment by isidore** [comment]
Also is the directory what you where you would expect that approved file to be?
/opt/jetbrains/teamcity/buildAgent/work/c1bbf18794ed62ea/./src/itest/java/tests

**Comment by mike03081972** [comment]
Hi,

Yes, the approved file is also commit to GIT and the location is correct on the build machine.

**Comment by isidore** [comment]
can you confirm that the approved file is getting copied there?

**Comment by mike03081972** [comment]
Hi,
Sorry for the delay !
I have checked the files on the linux build machine, and all seems to be OK.

Here's what I can see in the folder "/opt/jetbrains/teamcity/buildAgent/work/c1bbf18794ed62ea/./src/itest/java/tests/" :
- TestApprovals.java => contains the test code
- TestApprovals.TestApproval.approved.txt => contains the correct string
- TestApprovals.TestApproval.received.txt => contains the correct string

**Comment by mike03081972** [comment]
HI, Any idéal ?

**Comment by isidore** [comment]
not sure would you be up for a skype call tomorrow?

Llewellyn Falco
www.approvaltests.com

**Comment by mike03081972** [comment]
Hi, I was not at work yesterday.

I'm on another work, I will switch back after to this problem. I will tell
you if i'm ready for skyping.

But before, I want to make a test directly on a dev machine running under
Linux with IntelliJ installed to try to reproduce !

Thanks.

2017-10-11 22:15 GMT+02:00 Llewellyn Falco <notifications@github.com>:

**Comment by mike03081972** [comment]
Hi,

I have found the problem. There was a CaseSensitive problem.

The approved file was not the same on my windows or on the Linux part.

```
Approved:/opt/jetbrains/teamcity/buildAgent/work/c1bbf18794ed62ea/./src/itest/java/tests/TestApprovals.TestApproval.approved.txt
  Received:/opt/jetbrains/teamcity/buildAgent/work/c1bbf18794ed62ea/./src/itest/java/tests/TestApprovals.testApproval.received.txt
```

Commited file : TestApprovals.TestApproval.approved.txt
File on Linux : TestApprovals.testApproval.approved.txt

Don't know how this happended !
