### ISSUE TITLE
Recommended Kotlin directory structure is unsupported

### ISSUE THREAD

**Issue by micheljung** [approvals/ApprovalTests.Java#352]
From the [Kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html#directory-structure):

> # Source code organization
> ## Directory Structure
> In pure Kotlin projects, the recommended directory structure follows the package structure with the common root package omitted. For example, if all the code in the project is in the `org.example.kotlin` package and its subpackages, files with the `org.example.kotlin` package should be placed directly under the source root, and files in `org.example.kotlin.network.socket` should be in the `network/socket` subdirectory of the source root.

However, if you do this, you get:

```
Didn't find org.example.kotlin.network.socket.ExampleTest under C:\work\example
com.spun.util.FormattedException: org.example.kotlin.network.socket.ExampleTest under C:\work\example
	at app//com.spun.util.ClassUtils.getSourceDirectory(ClassUtils.java:103)
	at app//com.spun.util.ClassUtils.getSourceDirectory(ClassUtils.java:108)
	at app//com.spun.util.tests.TestUtils.getInfo(TestUtils.java:214)
	at app//com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:201)
	at app//com.spun.util.tests.TestUtils.getCurrentFileForMethod(TestUtils.java:193)
	at app//org.approvaltests.namer.StackTraceNamer.<init>(StackTraceNamer.java:17)
	at app//org.approvaltests.Approvals$1.load(Approvals.java:41)
	at app//org.approvaltests.Approvals$1.load(Approvals.java:38)
	at app//org.approvaltests.Approvals.createApprovalNamer(Approvals.java:257)
	at app//com.spun.util.ArrayUtils.getOrElse(ArrayUtils.java:302)
	at app//org.approvaltests.core.Options$FileOptions.getNamer(Options.java:104)
	at app//org.approvaltests.Approvals.verify(Approvals.java:183)
	at app//org.approvaltests.Approvals.verify(Approvals.java:50)
	at app//org.approvaltests.Approvals.verify(Approvals.java:59)
	at app//org.approvaltests.combinations.CombinationsHelper.verifyAllCombinations(CombinationsHelper.java:27)
	at app//org.approvaltests.combinations.CombinationApprovals.verifyAllCombinations(CombinationApprovals.java:205)
	at app//org.approvaltests.combinations.CombinationApprovals.verifyAllCombinations(CombinationApprovals.java:194)
	at app//org.approvaltests.combinations.CombinationApprovals.verifyAllCombinations(CombinationApprovals.java:50)
```

**Comment by LarsEckart** [comment]
hello,

any chance you can point us to a project that uses that structure, or perhaps even create a project with just a few files to play around with this use-case?

**Comment by micheljung** [comment]
Will do

**Comment by LarsEckart** [comment]
oh wow, skipping the folders for root level but still declaring package for them, now I understand. That will be interesting.

**Comment by ScottBob** [comment]
I think Kotlin now works. See https://github.com/[approvals/Approvaltests.Kotlin.StarterProject. If not, please reopen.

- Llewellyn, Jay, and Scott
